/*
 * Copyright (C) 2026 The X-ROM Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Tests for common/crypto/Sha256.cpp.
//
// Every expected digest in this file is a published vector or was produced by
// `openssl dgst -sha256`. None of them was produced by the implementation under
// test, which is the only property that makes these assertions worth anything: a
// digest generated by the same code that is being checked would pass no matter
// how wrong that code was.
//
// The padding-boundary cases (55, 56, 57, 63, 64, 65, 119, 120 bytes) are the
// ones that matter most. SHA-256 appends a length suffix and pads to a 64-byte
// block, and an implementation with an off-by-one in that logic produces correct
// digests for most inputs and wrong ones at exactly those lengths.

#include "Sha256.h"

#include <algorithm>
#include <cstdio>
#include <string>
#include <vector>

#include "gtest/gtest.h"

namespace {

using ::xrom::crypto::Sha256;
using ::xrom::crypto::Sha256Digest;

std::string Hex(const std::string& input) {
  return Sha256::ToHex(Sha256::Hash(input.data(), input.size()));
}

std::string Repeated(char byte, size_t count) { return std::string(count, byte); }

}  // namespace

// ---------------------------------------------------------------------------
// FIPS 180-4 / NIST CAVP published vectors
// ---------------------------------------------------------------------------

TEST(Sha256, EmptyString) {
  EXPECT_EQ(Hex(""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
}

TEST(Sha256, Abc) {
  EXPECT_EQ(Hex("abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
}

TEST(Sha256, FortyEightBytes) {
  // The standard three-block vector.
  EXPECT_EQ(Hex("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1");
}

TEST(Sha256, OneMillionA) {
  // Slow on purpose: 1 MiB exercises the streaming path and the 64-bit length
  // counter in the padding, which a 32-bit length would get wrong.
  EXPECT_EQ(Hex(Repeated('a', 1000000)),
            "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0");
}

// ---------------------------------------------------------------------------
// Padding boundaries. Each of these was cross-checked against
// `printf '%s' <n a's> | openssl dgst -sha256`.
// ---------------------------------------------------------------------------

TEST(Sha256, PaddingBoundaries) {
  struct Case {
    size_t length;
    const char* expected;
  };
  // 55 = last length that fits a single block with the 0x80 and the 8-byte
  // suffix; 56 and 57 spill into a second block; 63/64/65 straddle the block
  // edge itself; 119/120 are the same boundaries one block later.
  const Case cases[] = {
      {1, "ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"},
      {55, "9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318"},
      {56, "b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a"},
      {57, "f13b2d724659eb3bf47f2dd6af1accc87b81f09f59f2b75e5c0bed6589dfe8c6"},
      {63, "7d3e74a05d7db15bce4ad9ec0658ea98e3f06eeecf16b4c6fff2da457ddc2f34"},
      {64, "ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb"},
      {65, "635361c48bb9eab14198e76ea8ab7f1a41685d6ad62aa9146d301d4f17eb0ae0"},
      {119, "31eba51c313a5c08226adf18d4a359cfdfd8d2e816b13f4af952f7ea6584dcfb"},
      {120, "2f3d335432c70b580af0e8e1b3674a7c020d683aa5f73aaaedfdc55af904c21c"},
      {1000, "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3"},
  };
  for (const Case& test_case : cases) {
    const std::string actual = Hex(Repeated('a', test_case.length));
    EXPECT_EQ(actual, std::string(test_case.expected)) << "length " << test_case.length;
  }
}

// ---------------------------------------------------------------------------
// Incremental use
// ---------------------------------------------------------------------------

TEST(Sha256, IncrementalMatchesOneShot) {
  const std::string whole = Repeated('x', 5000);
  Sha256 hasher;
  for (size_t offset = 0; offset < whole.size(); offset += 7) {
    const size_t length = std::min<size_t>(7, whole.size() - offset);
    hasher.Update(whole.data() + offset, length);
  }
  EXPECT_EQ(Sha256::ToHex(hasher.Finalize()), Sha256::ToHex(Sha256::Hash(whole)));
}

TEST(Sha256, UpdateByOddChunkSizes) {
  // 64 is the block size and 56/57 are the padding boundaries, so hashing the
  // same data in chunks of every awkward size must give one answer.
  const std::string data = Repeated('q', 1000);
  const std::string expected = Sha256::ToHex(Sha256::Hash(data));
  for (const size_t chunk : {1u, 7u, 31u, 55u, 56u, 57u, 63u, 64u, 65u, 127u, 128u, 999u}) {
    Sha256 hasher;
    for (size_t offset = 0; offset < data.size(); offset += chunk) {
      hasher.Update(data.data() + offset, std::min(chunk, data.size() - offset));
    }
    EXPECT_EQ(Sha256::ToHex(hasher.Finalize()), expected) << "chunk " << chunk;
  }
}

TEST(Sha256, FinalizeResetsTheState) {
  Sha256 hasher;
  hasher.Update("abc");
  const std::string first = Sha256::ToHex(hasher.Finalize());
  hasher.Update("abc");
  const std::string second = Sha256::ToHex(hasher.Finalize());
  EXPECT_EQ(first, second);
  EXPECT_EQ(first, Hex("abc"));
}

TEST(Sha256, BytesHashedTracksTheInput) {
  Sha256 hasher;
  EXPECT_EQ(hasher.bytes_hashed(), 0u);
  hasher.Update("0123456789");
  EXPECT_EQ(hasher.bytes_hashed(), 10u);
  hasher.Update("abc");
  EXPECT_EQ(hasher.bytes_hashed(), 13u);
  hasher.Finalize();
  EXPECT_EQ(hasher.bytes_hashed(), 0u);
}

TEST(Sha256, ZeroLengthUpdateIsANoOp) {
  Sha256 hasher;
  hasher.Update("abc", 3);
  hasher.Update("", 0);
  hasher.Update(nullptr, 0);
  EXPECT_EQ(Sha256::ToHex(hasher.Finalize()), Hex("abc"));
}

// ---------------------------------------------------------------------------
// Hex conversion
// ---------------------------------------------------------------------------

TEST(Sha256, HexRoundTrip) {
  const Sha256Digest digest = Sha256::Hash("round trip");
  Sha256Digest parsed{};
  EXPECT_TRUE(Sha256::FromHex(Sha256::ToHex(digest), &parsed));
  EXPECT_TRUE(Sha256::Equal(digest, parsed));
}

TEST(Sha256, FromHexIsStrict) {
  const std::string valid = Repeated('a', 64);
  Sha256Digest out{};
  EXPECT_TRUE(Sha256::FromHex(valid, &out));

  // Uppercase is accepted because manifests are written by tools that differ in
  // case, and rejecting one would make a valid digest look invalid.
  EXPECT_TRUE(Sha256::FromHex(Repeated('A', 64), &out));

  EXPECT_FALSE(Sha256::FromHex(Repeated('a', 63), &out));
  EXPECT_FALSE(Sha256::FromHex(Repeated('a', 65), &out));
  EXPECT_FALSE(Sha256::FromHex("", &out));
  EXPECT_FALSE(Sha256::FromHex(Repeated('g', 64), &out));       // not hex
  EXPECT_FALSE(Sha256::FromHex(Repeated('a', 62) + " z", &out));  // embedded space
  EXPECT_FALSE(Sha256::FromHex(Repeated('a', 62) + "\n\n", &out));
}

TEST(Sha256, EqualIsNotFooledByPrefixes) {
  const Sha256Digest a = Sha256::Hash("a");
  const Sha256Digest b = Sha256::Hash("b");
  EXPECT_TRUE(Sha256::Equal(a, a));
  EXPECT_FALSE(Sha256::Equal(a, b));
}
